version: 0.2

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - bundle exec htmlproofer _site --check-html --disable-external
  post_build:
    commands:
      - aws s3 sync _site/ s3://optatours.com
      - aws cloudfront create-invalidation --distribution-id E3PGDB9FVBJER1 --path "/*"
